"""empty message

Revision ID: 098f56709714
Revises: f6735e7cf47f
Create Date: 2024-10-14 16:57:26.008681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098f56709714'
down_revision = 'f6735e7cf47f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint('bookmarks_company_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('bookmarks_developer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'developers', ['developer_id'], ['user_id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('tecnologies', sa.String(length=200), nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')
        batch_op.drop_column('id')

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_constraint('offers_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['user_id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('projects_developer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'developers', ['developer_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('projects_developer_id_fkey', 'developers', ['developer_id'], ['id'])

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('offers_company_id_fkey', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('tecnologies')
        batch_op.drop_column('experience')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('companies_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bookmarks_developer_id_fkey', 'developers', ['developer_id'], ['id'])
        batch_op.create_foreign_key('bookmarks_company_id_fkey', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###
