"""empty message

Revision ID: 4258bb2e1d4b
Revises: b491510f354e
Create Date: 2024-10-21 19:49:04.763471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4258bb2e1d4b'
down_revision = 'b491510f354e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('logo')

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=80),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testimony', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=250), nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('testimony')

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('role')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
