"""empty message

Revision ID: 4fae002d715c
Revises: f4a44b3b8701
Create Date: 2024-10-22 20:37:05.085946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fae002d715c'
down_revision = 'f4a44b3b8701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lenguages', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('lenguages')

    # ### end Alembic commands ###
