"""empty message

Revision ID: 566acb1013b6
Revises: 8df60005bc4a
Create Date: 2024-10-22 23:37:30.171637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566acb1013b6'
down_revision = '8df60005bc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimun_requirements', sa.String(length=120), nullable=True))
        batch_op.drop_column('minimum_requirements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_requirements', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('minimun_requirements')

    # ### end Alembic commands ###
