"""empty message

Revision ID: 7d499319effc
Revises: e3618749ed5a
Create Date: 2024-10-29 23:21:40.034755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d499319effc'
down_revision = 'e3618749ed5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('application_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('status')
        batch_op.drop_column('resume_url')

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_url', sa.String(length=500)))
        batch_op.add_column(sa.Column('status', sa.String(length=20), default='Pendiente'))
        batch_op.alter_column('experience',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=True)

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('posted_date',
               existing_type=sa.DATE())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('posted_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.alter_column('experience',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('resume_url')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('application_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
