"""empty message

Revision ID: 8df60005bc4a
Revises: 4fae002d715c
Create Date: 2024-10-22 22:32:36.134729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df60005bc4a'
down_revision = '4fae002d715c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', sa.String(length=20), nullable=True))
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('lenguages')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lenguages', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.alter_column('company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('languages')

    # ### end Alembic commands ###
