"""empty message

Revision ID: e637e8d42072
Revises: ff2af211d590
Create Date: 2024-10-14 15:19:47.184979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e637e8d42072'
down_revision = 'ff2af211d590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
