"""empty message

Revision ID: f4a44b3b8701
Revises: 4258bb2e1d4b
Create Date: 2024-10-22 02:57:20.886159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4a44b3b8701'
down_revision = '4258bb2e1d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium', sa.Boolean(), nullable=True))

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium', sa.Boolean(), nullable=True))

    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modality', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('posted_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('education_level', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('minimun_experience', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('minimum_requirements', sa.String(length=120), nullable=True))
        batch_op.alter_column('salary',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('contract_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('contract_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('salary',
               existing_type=sa.String(length=7),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('minimum_requirements')
        batch_op.drop_column('minimun_experience')
        batch_op.drop_column('education_level')
        batch_op.drop_column('posted_date')
        batch_op.drop_column('modality')

    with op.batch_alter_table('developers', schema=None) as batch_op:
        batch_op.drop_column('premium')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('premium')

    # ### end Alembic commands ###
